# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QFrame,
    QHBoxLayout, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QPushButton, QScrollArea, QSizePolicy,
    QStackedWidget, QTabWidget, QTableWidget, QTableWidgetItem,
    QVBoxLayout, QWidget)

from image_drop_label import ImageDropLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 700)
        MainWindow.setStyleSheet(u"#bao_cao_menu,\n"
"#hoa_don_menu,\n"
"#khach_hang_menu,\n"
"#nhan_vien_menu,\n"
"#phieu_hang_menu,\n"
"#kho_menu {\n"
"    background-color: #3498db;\n"
"    border: 2px solid black;\n"
"}\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 1200, 50))
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.kho_menu = QFrame(self.widget)
        self.kho_menu.setObjectName(u"kho_menu")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kho_menu.sizePolicy().hasHeightForWidth())
        self.kho_menu.setSizePolicy(sizePolicy)
        self.kho_menu.setFrameShape(QFrame.Shape.StyledPanel)
        self.kho_menu.setFrameShadow(QFrame.Shadow.Raised)
        self.kho_button = QLabel(self.kho_menu)
        self.kho_button.setObjectName(u"kho_button")
        self.kho_button.setGeometry(QRect(10, 0, 201, 50))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.kho_button.setFont(font)
        self.kho_button.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.kho_menu)

        self.hoa_don_menu = QFrame(self.widget)
        self.hoa_don_menu.setObjectName(u"hoa_don_menu")
        sizePolicy.setHeightForWidth(self.hoa_don_menu.sizePolicy().hasHeightForWidth())
        self.hoa_don_menu.setSizePolicy(sizePolicy)
        self.hoa_don_menu.setFrameShape(QFrame.Shape.StyledPanel)
        self.hoa_don_menu.setFrameShadow(QFrame.Shadow.Raised)
        self.hoa_don_button = QLabel(self.hoa_don_menu)
        self.hoa_don_button.setObjectName(u"hoa_don_button")
        self.hoa_don_button.setGeometry(QRect(10, 0, 201, 50))
        self.hoa_don_button.setFont(font)
        self.hoa_don_button.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.hoa_don_menu)

        self.bao_cao_menu = QFrame(self.widget)
        self.bao_cao_menu.setObjectName(u"bao_cao_menu")
        sizePolicy.setHeightForWidth(self.bao_cao_menu.sizePolicy().hasHeightForWidth())
        self.bao_cao_menu.setSizePolicy(sizePolicy)
        self.bao_cao_menu.setFrameShape(QFrame.Shape.StyledPanel)
        self.bao_cao_menu.setFrameShadow(QFrame.Shadow.Raised)
        self.cao_cao_button = QLabel(self.bao_cao_menu)
        self.cao_cao_button.setObjectName(u"cao_cao_button")
        self.cao_cao_button.setGeometry(QRect(10, 0, 201, 50))
        self.cao_cao_button.setFont(font)
        self.cao_cao_button.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.bao_cao_menu)

        self.khach_hang_menu = QFrame(self.widget)
        self.khach_hang_menu.setObjectName(u"khach_hang_menu")
        sizePolicy.setHeightForWidth(self.khach_hang_menu.sizePolicy().hasHeightForWidth())
        self.khach_hang_menu.setSizePolicy(sizePolicy)
        self.khach_hang_menu.setFrameShape(QFrame.Shape.StyledPanel)
        self.khach_hang_menu.setFrameShadow(QFrame.Shadow.Raised)
        self.khach_hang_btn = QLabel(self.khach_hang_menu)
        self.khach_hang_btn.setObjectName(u"khach_hang_btn")
        self.khach_hang_btn.setGeometry(QRect(10, 0, 201, 50))
        self.khach_hang_btn.setFont(font)
        self.khach_hang_btn.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.khach_hang_menu)

        self.phieu_hang_menu = QFrame(self.widget)
        self.phieu_hang_menu.setObjectName(u"phieu_hang_menu")
        sizePolicy.setHeightForWidth(self.phieu_hang_menu.sizePolicy().hasHeightForWidth())
        self.phieu_hang_menu.setSizePolicy(sizePolicy)
        self.phieu_hang_menu.setFrameShape(QFrame.Shape.StyledPanel)
        self.phieu_hang_menu.setFrameShadow(QFrame.Shadow.Raised)
        self.phieu_hang_button = QLabel(self.phieu_hang_menu)
        self.phieu_hang_button.setObjectName(u"phieu_hang_button")
        self.phieu_hang_button.setGeometry(QRect(10, 0, 201, 50))
        self.phieu_hang_button.setFont(font)
        self.phieu_hang_button.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.phieu_hang_menu)

        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 50, 1200, 651))
        self.phieu_hang_screen = QWidget()
        self.phieu_hang_screen.setObjectName(u"phieu_hang_screen")
        self.scrollArea = QScrollArea(self.phieu_hang_screen)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 30, 580, 580))
        self.scrollArea.setWidgetResizable(True)
        self.danh_sach_san_pham = QWidget()
        self.danh_sach_san_pham.setObjectName(u"danh_sach_san_pham")
        self.danh_sach_san_pham.setGeometry(QRect(0, 0, 578, 578))
        self.scrollArea.setWidget(self.danh_sach_san_pham)
        self.tab_phieu_hang = QTabWidget(self.phieu_hang_screen)
        self.tab_phieu_hang.setObjectName(u"tab_phieu_hang")
        self.tab_phieu_hang.setGeometry(QRect(610, 30, 581, 581))
        self.create_ticket_button = QPushButton(self.phieu_hang_screen)
        self.create_ticket_button.setObjectName(u"create_ticket_button")
        self.create_ticket_button.setGeometry(QRect(610, 10, 75, 24))
        self.search_input = QLineEdit(self.phieu_hang_screen)
        self.search_input.setObjectName(u"search_input")
        self.search_input.setGeometry(QRect(10, 0, 301, 31))
        self.search_input.setLocale(QLocale(QLocale.Vietnamese, QLocale.Vietnam))
        self.search_input.setInputMask(u"")
        self.search_input.setText(u"")
        self.search_input.setReadOnly(False)
        self.cap_nhat = QPushButton(self.phieu_hang_screen)
        self.cap_nhat.setObjectName(u"cap_nhat")
        self.cap_nhat.setGeometry(QRect(330, 0, 93, 29))
        self.chon_phieu_hang = QLabel(self.phieu_hang_screen)
        self.chon_phieu_hang.setObjectName(u"chon_phieu_hang")
        self.chon_phieu_hang.setGeometry(QRect(960, 0, 241, 16))
        self.chon_phieu_hang.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.stackedWidget.addWidget(self.phieu_hang_screen)
        self.nhan_vien_screen = QWidget()
        self.nhan_vien_screen.setObjectName(u"nhan_vien_screen")
        self.stackedWidget.addWidget(self.nhan_vien_screen)
        self.hoa_don_screen = QWidget()
        self.hoa_don_screen.setObjectName(u"hoa_don_screen")
        self.table_hoa_don = QTableWidget(self.hoa_don_screen)
        if (self.table_hoa_don.columnCount() < 5):
            self.table_hoa_don.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.table_hoa_don.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.table_hoa_don.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.table_hoa_don.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.table_hoa_don.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.table_hoa_don.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.table_hoa_don.setObjectName(u"table_hoa_don")
        self.table_hoa_don.setGeometry(QRect(20, 20, 651, 581))
        self.frame_4 = QFrame(self.hoa_don_screen)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(720, 20, 361, 71))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.frame_2 = QFrame(self.frame_4)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout_2.addWidget(self.label_2)

        self.from_date_edit = QDateEdit(self.frame_2)
        self.from_date_edit.setObjectName(u"from_date_edit")

        self.horizontalLayout_2.addWidget(self.from_date_edit)


        self.horizontalLayout_4.addWidget(self.frame_2)

        self.frame_3 = QFrame(self.frame_4)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout_3.addWidget(self.label_3)

        self.to_date_edit = QDateEdit(self.frame_3)
        self.to_date_edit.setObjectName(u"to_date_edit")

        self.horizontalLayout_3.addWidget(self.to_date_edit)


        self.horizontalLayout_4.addWidget(self.frame_3)

        self.show_date_from_to_button = QPushButton(self.hoa_don_screen)
        self.show_date_from_to_button.setObjectName(u"show_date_from_to_button")
        self.show_date_from_to_button.setGeometry(QRect(850, 90, 91, 41))
        self.show_date_from_to_button.setFont(font)
        self.frame_5 = QFrame(self.hoa_don_screen)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(750, 120, 301, 161))
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.sort_from_small_to_big_button = QPushButton(self.frame_5)
        self.sort_from_small_to_big_button.setObjectName(u"sort_from_small_to_big_button")
        self.sort_from_small_to_big_button.setFont(font)
        self.sort_from_small_to_big_button.setStyleSheet(u"color: rgb(0, 255, 0);")

        self.horizontalLayout_5.addWidget(self.sort_from_small_to_big_button)

        self.sort_from_big_to_small_button = QPushButton(self.frame_5)
        self.sort_from_big_to_small_button.setObjectName(u"sort_from_big_to_small_button")
        self.sort_from_big_to_small_button.setFont(font)
        self.sort_from_big_to_small_button.setStyleSheet(u"color: rgb(255, 0, 0);")

        self.horizontalLayout_5.addWidget(self.sort_from_big_to_small_button)

        self.refresh_hoa_don_button = QPushButton(self.hoa_don_screen)
        self.refresh_hoa_don_button.setObjectName(u"refresh_hoa_don_button")
        self.refresh_hoa_don_button.setGeometry(QRect(770, 280, 251, 101))
        self.chon_hoa_don = QLabel(self.hoa_don_screen)
        self.chon_hoa_don.setObjectName(u"chon_hoa_don")
        self.chon_hoa_don.setGeometry(QRect(240, 0, 241, 16))
        self.chon_hoa_don.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.stackedWidget.addWidget(self.hoa_don_screen)
        self.bao_cao_screen = QWidget()
        self.bao_cao_screen.setObjectName(u"bao_cao_screen")
        self.horizontalLayoutWidget = QWidget(self.bao_cao_screen)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 10, 331, 51))
        self.Chonthoigian = QHBoxLayout(self.horizontalLayoutWidget)
        self.Chonthoigian.setObjectName(u"Chonthoigian")
        self.Chonthoigian.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.Chonthoigian.addWidget(self.label)

        self.thang = QComboBox(self.horizontalLayoutWidget)
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.addItem("")
        self.thang.setObjectName(u"thang")

        self.Chonthoigian.addWidget(self.thang)

        self.nam = QComboBox(self.horizontalLayoutWidget)
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.addItem("")
        self.nam.setObjectName(u"nam")

        self.Chonthoigian.addWidget(self.nam)

        self.doanhthutheonhom = QTableWidget(self.bao_cao_screen)
        self.doanhthutheonhom.setObjectName(u"doanhthutheonhom")
        self.doanhthutheonhom.setGeometry(QRect(360, 20, 471, 311))
        self.tongdt = QFrame(self.bao_cao_screen)
        self.tongdt.setObjectName(u"tongdt")
        self.tongdt.setGeometry(QRect(40, 60, 311, 51))
        self.tongdt.setFrameShape(QFrame.Shape.StyledPanel)
        self.tongdt.setFrameShadow(QFrame.Shadow.Raised)
        self.label_4 = QLabel(self.tongdt)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 151, 31))
        self.label_7 = QLabel(self.tongdt)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 10, 171, 31))
        self.tongdt_2 = QFrame(self.bao_cao_screen)
        self.tongdt_2.setObjectName(u"tongdt_2")
        self.tongdt_2.setGeometry(QRect(40, 110, 311, 51))
        self.tongdt_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.tongdt_2.setFrameShadow(QFrame.Shadow.Raised)
        self.label_6 = QLabel(self.tongdt_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 10, 171, 31))
        self.label_8 = QLabel(self.tongdt_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(200, 10, 111, 31))
        self.tongdt_3 = QFrame(self.bao_cao_screen)
        self.tongdt_3.setObjectName(u"tongdt_3")
        self.tongdt_3.setGeometry(QRect(40, 220, 311, 51))
        self.tongdt_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.tongdt_3.setFrameShadow(QFrame.Shadow.Raised)
        self.label_9 = QLabel(self.tongdt_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 171, 31))
        self.label_10 = QLabel(self.tongdt_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(200, 10, 111, 31))
        self.loinhuantheonhom = QTableWidget(self.bao_cao_screen)
        self.loinhuantheonhom.setObjectName(u"loinhuantheonhom")
        self.loinhuantheonhom.setGeometry(QRect(850, 20, 321, 61))
        self.tongdt_4 = QFrame(self.bao_cao_screen)
        self.tongdt_4.setObjectName(u"tongdt_4")
        self.tongdt_4.setGeometry(QRect(40, 280, 311, 51))
        self.tongdt_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.tongdt_4.setFrameShadow(QFrame.Shadow.Raised)
        self.label_11 = QLabel(self.tongdt_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 171, 31))
        self.label_12 = QLabel(self.tongdt_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(200, 10, 111, 31))
        self.dtcacthangtrongnam = QTableWidget(self.bao_cao_screen)
        self.dtcacthangtrongnam.setObjectName(u"dtcacthangtrongnam")
        self.dtcacthangtrongnam.setGeometry(QRect(40, 340, 571, 281))
        self.thongkemuaban = QTableWidget(self.bao_cao_screen)
        self.thongkemuaban.setObjectName(u"thongkemuaban")
        self.thongkemuaban.setGeometry(QRect(630, 340, 411, 281))
        self.xuat_bao_cao_button = QPushButton(self.bao_cao_screen)
        self.xuat_bao_cao_button.setObjectName(u"xuat_bao_cao_button")
        self.xuat_bao_cao_button.setGeometry(QRect(1050, 430, 111, 41))
        font1 = QFont()
        font1.setBold(True)
        self.xuat_bao_cao_button.setFont(font1)
        self.xuat_du_lieu_button = QPushButton(self.bao_cao_screen)
        self.xuat_du_lieu_button.setObjectName(u"xuat_du_lieu_button")
        self.xuat_du_lieu_button.setGeometry(QRect(1050, 500, 111, 41))
        self.xuat_du_lieu_button.setFont(font1)
        self.sanphambanchay = QTableWidget(self.bao_cao_screen)
        self.sanphambanchay.setObjectName(u"sanphambanchay")
        self.sanphambanchay.setGeometry(QRect(850, 90, 321, 231))
        self.label_13 = QLabel(self.bao_cao_screen)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(1030, 30, 151, 31))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.label_13.setFont(font2)
        self.label_14 = QLabel(self.bao_cao_screen)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(870, 30, 171, 31))
        self.label_14.setFont(font2)
        self.tongdt_5 = QFrame(self.bao_cao_screen)
        self.tongdt_5.setObjectName(u"tongdt_5")
        self.tongdt_5.setGeometry(QRect(40, 160, 311, 51))
        self.tongdt_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.tongdt_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_15 = QLabel(self.tongdt_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 10, 171, 31))
        self.label_16 = QLabel(self.tongdt_5)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(200, 10, 111, 31))
        self.chon_bao_cao = QLabel(self.bao_cao_screen)
        self.chon_bao_cao.setObjectName(u"chon_bao_cao")
        self.chon_bao_cao.setGeometry(QRect(480, 0, 241, 16))
        self.chon_bao_cao.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.stackedWidget.addWidget(self.bao_cao_screen)
        self.kho_screen = QWidget()
        self.kho_screen.setObjectName(u"kho_screen")
        self.kho_table_widget = QTableWidget(self.kho_screen)
        if (self.kho_table_widget.columnCount() < 7):
            self.kho_table_widget.setColumnCount(7)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(4, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(5, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.kho_table_widget.setHorizontalHeaderItem(6, __qtablewidgetitem11)
        self.kho_table_widget.setObjectName(u"kho_table_widget")
        self.kho_table_widget.setGeometry(QRect(10, 60, 701, 581))
        self.kho_stackedWidget = QStackedWidget(self.kho_screen)
        self.kho_stackedWidget.setObjectName(u"kho_stackedWidget")
        self.kho_stackedWidget.setGeometry(QRect(740, 50, 451, 561))
        self.kho_chinh_sua_page = QWidget()
        self.kho_chinh_sua_page.setObjectName(u"kho_chinh_sua_page")
        self.frame_6 = QFrame(self.kho_chinh_sua_page)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(0, 0, 451, 301))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.kho_chinh_sua_id_san_pham_line_edit = QLineEdit(self.frame_6)
        self.kho_chinh_sua_id_san_pham_line_edit.setObjectName(u"kho_chinh_sua_id_san_pham_line_edit")

        self.verticalLayout_2.addWidget(self.kho_chinh_sua_id_san_pham_line_edit)

        self.kho_chinh_sua_ten_san_pham_line_edit = QLineEdit(self.frame_6)
        self.kho_chinh_sua_ten_san_pham_line_edit.setObjectName(u"kho_chinh_sua_ten_san_pham_line_edit")

        self.verticalLayout_2.addWidget(self.kho_chinh_sua_ten_san_pham_line_edit)

        self.kho_chinh_sua_id_danh_muc_combobox = QComboBox(self.frame_6)
        self.kho_chinh_sua_id_danh_muc_combobox.setObjectName(u"kho_chinh_sua_id_danh_muc_combobox")

        self.verticalLayout_2.addWidget(self.kho_chinh_sua_id_danh_muc_combobox)

        self.kho_chinh_sua_gia_san_pham_line_edit = QLineEdit(self.frame_6)
        self.kho_chinh_sua_gia_san_pham_line_edit.setObjectName(u"kho_chinh_sua_gia_san_pham_line_edit")

        self.verticalLayout_2.addWidget(self.kho_chinh_sua_gia_san_pham_line_edit)

        self.kho_chinh_sua_so_luong_ton_kho_line_edit = QLineEdit(self.frame_6)
        self.kho_chinh_sua_so_luong_ton_kho_line_edit.setObjectName(u"kho_chinh_sua_so_luong_ton_kho_line_edit")

        self.verticalLayout_2.addWidget(self.kho_chinh_sua_so_luong_ton_kho_line_edit)

        self.kho_chinh_sua_mo_ta_san_pham_line_edit = QLineEdit(self.frame_6)
        self.kho_chinh_sua_mo_ta_san_pham_line_edit.setObjectName(u"kho_chinh_sua_mo_ta_san_pham_line_edit")

        self.verticalLayout_2.addWidget(self.kho_chinh_sua_mo_ta_san_pham_line_edit)

        self.kho_chinh_sua_image_drop_label = ImageDropLabel(self.kho_chinh_sua_page)
        self.kho_chinh_sua_image_drop_label.setObjectName(u"kho_chinh_sua_image_drop_label")
        self.kho_chinh_sua_image_drop_label.setGeometry(QRect(10, 310, 431, 91))
        self.kho_chinh_sua_image_drop_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.kho_chinh_sua_sua_button = QPushButton(self.kho_chinh_sua_page)
        self.kho_chinh_sua_sua_button.setObjectName(u"kho_chinh_sua_sua_button")
        self.kho_chinh_sua_sua_button.setGeometry(QRect(110, 420, 231, 51))
        self.kho_save_button = QPushButton(self.kho_chinh_sua_page)
        self.kho_save_button.setObjectName(u"kho_save_button")
        self.kho_save_button.setGeometry(QRect(110, 480, 231, 51))
        self.kho_stackedWidget.addWidget(self.kho_chinh_sua_page)
        self.kho_nhap_hang_page = QWidget()
        self.kho_nhap_hang_page.setObjectName(u"kho_nhap_hang_page")
        self.frame_7 = QFrame(self.kho_nhap_hang_page)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(0, 0, 451, 301))
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.kho_nhap_hang_id_san_pham_line_edit = QLineEdit(self.frame_7)
        self.kho_nhap_hang_id_san_pham_line_edit.setObjectName(u"kho_nhap_hang_id_san_pham_line_edit")

        self.verticalLayout_3.addWidget(self.kho_nhap_hang_id_san_pham_line_edit)

        self.kho_nhap_hang_ten_san_pham_line_edit = QLineEdit(self.frame_7)
        self.kho_nhap_hang_ten_san_pham_line_edit.setObjectName(u"kho_nhap_hang_ten_san_pham_line_edit")

        self.verticalLayout_3.addWidget(self.kho_nhap_hang_ten_san_pham_line_edit)

        self.kho_nhap_hang_so_luong_ton_kho_line_edit = QLineEdit(self.frame_7)
        self.kho_nhap_hang_so_luong_ton_kho_line_edit.setObjectName(u"kho_nhap_hang_so_luong_ton_kho_line_edit")

        self.verticalLayout_3.addWidget(self.kho_nhap_hang_so_luong_ton_kho_line_edit)

        self.kho_nhap_hang_so_luong_ton_kho_line_edit_2 = QLineEdit(self.frame_7)
        self.kho_nhap_hang_so_luong_ton_kho_line_edit_2.setObjectName(u"kho_nhap_hang_so_luong_ton_kho_line_edit_2")

        self.verticalLayout_3.addWidget(self.kho_nhap_hang_so_luong_ton_kho_line_edit_2)

        self.kho_nhap_hang_gia_nhap_san_pham_line_edit = QLineEdit(self.frame_7)
        self.kho_nhap_hang_gia_nhap_san_pham_line_edit.setObjectName(u"kho_nhap_hang_gia_nhap_san_pham_line_edit")

        self.verticalLayout_3.addWidget(self.kho_nhap_hang_gia_nhap_san_pham_line_edit)

        self.kho_nhap_hang_image_drop_label = ImageDropLabel(self.kho_nhap_hang_page)
        self.kho_nhap_hang_image_drop_label.setObjectName(u"kho_nhap_hang_image_drop_label")
        self.kho_nhap_hang_image_drop_label.setGeometry(QRect(10, 300, 431, 91))
        self.kho_nhap_hang_image_drop_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.kho_nhap_hang_nhap_button = QPushButton(self.kho_nhap_hang_page)
        self.kho_nhap_hang_nhap_button.setObjectName(u"kho_nhap_hang_nhap_button")
        self.kho_nhap_hang_nhap_button.setGeometry(QRect(60, 400, 331, 41))
        self.kho_stackedWidget.addWidget(self.kho_nhap_hang_page)
        self.widget_2 = QWidget(self.kho_screen)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(740, 10, 451, 42))
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.horizontalLayout_6 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.kho_chinh_sua_button = QPushButton(self.widget_2)
        self.kho_chinh_sua_button.setObjectName(u"kho_chinh_sua_button")
        sizePolicy.setHeightForWidth(self.kho_chinh_sua_button.sizePolicy().hasHeightForWidth())
        self.kho_chinh_sua_button.setSizePolicy(sizePolicy)

        self.horizontalLayout_6.addWidget(self.kho_chinh_sua_button)

        self.kho_nhap_hang_button = QPushButton(self.widget_2)
        self.kho_nhap_hang_button.setObjectName(u"kho_nhap_hang_button")
        sizePolicy.setHeightForWidth(self.kho_nhap_hang_button.sizePolicy().hasHeightForWidth())
        self.kho_nhap_hang_button.setSizePolicy(sizePolicy)

        self.horizontalLayout_6.addWidget(self.kho_nhap_hang_button)

        self.kho_tai_lai_san_pham_button = QPushButton(self.kho_screen)
        self.kho_tai_lai_san_pham_button.setObjectName(u"kho_tai_lai_san_pham_button")
        self.kho_tai_lai_san_pham_button.setGeometry(QRect(10, 20, 75, 31))
        self.kho_tai_lai_san_pham_button.setFont(font1)
        icon = QIcon()
        icon.addFile(u"../../Downloads/icons8-refresh-50.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.kho_tai_lai_san_pham_button.setIcon(icon)
        self.kho_xoa_san_pham_button = QPushButton(self.kho_screen)
        self.kho_xoa_san_pham_button.setObjectName(u"kho_xoa_san_pham_button")
        self.kho_xoa_san_pham_button.setGeometry(QRect(90, 20, 81, 31))
        self.kho_xoa_san_pham_button.setFont(font1)
        icon1 = QIcon()
        icon1.addFile(u"../../Downloads/icons8-delete-50.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.kho_xoa_san_pham_button.setIcon(icon1)
        self.kho_them_moi_button = QPushButton(self.kho_screen)
        self.kho_them_moi_button.setObjectName(u"kho_them_moi_button")
        self.kho_them_moi_button.setGeometry(QRect(177, 20, 81, 31))
        self.kho_them_moi_button.setFont(font1)
        self.kho_them_moi_button.setIcon(icon1)
        self.chon_kho = QLabel(self.kho_screen)
        self.chon_kho.setObjectName(u"chon_kho")
        self.chon_kho.setGeometry(QRect(0, 0, 241, 16))
        self.chon_kho.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.stackedWidget.addWidget(self.kho_screen)
        self.khach_hang_screen = QWidget()
        self.khach_hang_screen.setObjectName(u"khach_hang_screen")
        self.tableWidget = QTableWidget(self.khach_hang_screen)
        if (self.tableWidget.columnCount() < 6):
            self.tableWidget.setColumnCount(6)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem17)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(30, 70, 811, 531))
        self.add_button = QPushButton(self.khach_hang_screen)
        self.add_button.setObjectName(u"add_button")
        self.add_button.setGeometry(QRect(960, 380, 141, 51))
        self.add_button.setFont(font1)
        self.update_button = QPushButton(self.khach_hang_screen)
        self.update_button.setObjectName(u"update_button")
        self.update_button.setGeometry(QRect(960, 440, 141, 51))
        self.update_button.setFont(font1)
        self.delete_button = QPushButton(self.khach_hang_screen)
        self.delete_button.setObjectName(u"delete_button")
        self.delete_button.setGeometry(QRect(960, 500, 141, 51))
        self.delete_button.setFont(font1)
        self.frame = QFrame(self.khach_hang_screen)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(880, 30, 291, 341))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(9, 9, -1, -1)
        self.id_line_edit = QLineEdit(self.frame)
        self.id_line_edit.setObjectName(u"id_line_edit")
        sizePolicy.setHeightForWidth(self.id_line_edit.sizePolicy().hasHeightForWidth())
        self.id_line_edit.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.id_line_edit)

        self.name_line_edit = QLineEdit(self.frame)
        self.name_line_edit.setObjectName(u"name_line_edit")
        sizePolicy.setHeightForWidth(self.name_line_edit.sizePolicy().hasHeightForWidth())
        self.name_line_edit.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.name_line_edit)

        self.age_line_edit = QLineEdit(self.frame)
        self.age_line_edit.setObjectName(u"age_line_edit")
        sizePolicy.setHeightForWidth(self.age_line_edit.sizePolicy().hasHeightForWidth())
        self.age_line_edit.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.age_line_edit)

        self.gender_line_edit = QComboBox(self.frame)
        self.gender_line_edit.addItem("")
        self.gender_line_edit.addItem("")
        self.gender_line_edit.setObjectName(u"gender_line_edit")

        self.verticalLayout.addWidget(self.gender_line_edit)

        self.address_line_edit = QLineEdit(self.frame)
        self.address_line_edit.setObjectName(u"address_line_edit")
        sizePolicy.setHeightForWidth(self.address_line_edit.sizePolicy().hasHeightForWidth())
        self.address_line_edit.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.address_line_edit)

        self.phone_line_edit = QLineEdit(self.frame)
        self.phone_line_edit.setObjectName(u"phone_line_edit")
        sizePolicy.setHeightForWidth(self.phone_line_edit.sizePolicy().hasHeightForWidth())
        self.phone_line_edit.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.phone_line_edit)

        self.show_history_button = QPushButton(self.khach_hang_screen)
        self.show_history_button.setObjectName(u"show_history_button")
        self.show_history_button.setGeometry(QRect(960, 560, 141, 51))
        self.show_history_button.setFont(font1)
        self.search_khach_hang = QLineEdit(self.khach_hang_screen)
        self.search_khach_hang.setObjectName(u"search_khach_hang")
        self.search_khach_hang.setGeometry(QRect(30, 20, 391, 31))
        self.search_khach_hang.setLocale(QLocale(QLocale.Vietnamese, QLocale.Vietnam))
        self.search_khach_hang.setInputMask(u"")
        self.search_khach_hang.setText(u"")
        self.search_khach_hang.setReadOnly(False)
        self.chon_khach_hang = QLabel(self.khach_hang_screen)
        self.chon_khach_hang.setObjectName(u"chon_khach_hang")
        self.chon_khach_hang.setGeometry(QRect(720, 0, 241, 16))
        self.chon_khach_hang.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.them_khach_moi = QPushButton(self.khach_hang_screen)
        self.them_khach_moi.setObjectName(u"them_khach_moi")
        self.them_khach_moi.setGeometry(QRect(440, 20, 161, 31))
        self.stackedWidget.addWidget(self.khach_hang_screen)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.tab_phieu_hang.setCurrentIndex(-1)
        self.kho_stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ph\u1ea7n M\u1ec1m Qu\u1ea3n L\u00fd Shop Th\u1eddi Trang", None))
        self.kho_button.setText(QCoreApplication.translate("MainWindow", u"KHO", None))
        self.hoa_don_button.setText(QCoreApplication.translate("MainWindow", u"H\u00d3A \u0110\u01a0N", None))
        self.cao_cao_button.setText(QCoreApplication.translate("MainWindow", u"B\u00c1O C\u00c1O", None))
        self.khach_hang_btn.setText(QCoreApplication.translate("MainWindow", u"KH\u00c1CH H\u00c0NG", None))
        self.phieu_hang_button.setText(QCoreApplication.translate("MainWindow", u"PHI\u1ebeU H\u00c0NG", None))
        self.create_ticket_button.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.search_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"T\u00ecm ki\u1ebfm", None))
        self.cap_nhat.setText(QCoreApplication.translate("MainWindow", u"C\u1eadp Nh\u1eadt", None))
        self.chon_phieu_hang.setText("")
        ___qtablewidgetitem = self.table_hoa_don.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"ID H\u00f3a \u0110\u01a1n", None));
        ___qtablewidgetitem1 = self.table_hoa_don.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng Gi\u00e1 Tr\u1ecb", None));
        ___qtablewidgetitem2 = self.table_hoa_don.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"ID Kh\u00e1ch H\u00e0ng", None));
        ___qtablewidgetitem3 = self.table_hoa_don.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Lo\u1ea1i H\u00f3a \u0110\u01a1n", None));
        ___qtablewidgetitem4 = self.table_hoa_don.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Ng\u00e0y Giao D\u1ecbch", None));
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"T\u1eeb:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ebfn:", None))
        self.show_date_from_to_button.setText(QCoreApplication.translate("MainWindow", u"Xem ", None))
        self.sort_from_small_to_big_button.setText(QCoreApplication.translate("MainWindow", u"T\u0103ng D\u1ea7n", None))
        self.sort_from_big_to_small_button.setText(QCoreApplication.translate("MainWindow", u"Gi\u1ea3m D\u1ea7n", None))
        self.refresh_hoa_don_button.setText(QCoreApplication.translate("MainWindow", u"C\u1eacP NH\u1eacT L\u1ea0I H\u00d3A \u0110\u01a0N M\u1edaI NH\u1ea4T", None))
        self.chon_hoa_don.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn th\u1eddi gian", None))
        self.thang.setItemText(0, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 1", None))
        self.thang.setItemText(1, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 2", None))
        self.thang.setItemText(2, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 3", None))
        self.thang.setItemText(3, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 4", None))
        self.thang.setItemText(4, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 5", None))
        self.thang.setItemText(5, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 6", None))
        self.thang.setItemText(6, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 7", None))
        self.thang.setItemText(7, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 8", None))
        self.thang.setItemText(8, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 9", None))
        self.thang.setItemText(9, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 10", None))
        self.thang.setItemText(10, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 11", None))
        self.thang.setItemText(11, QCoreApplication.translate("MainWindow", u"Th\u00e1ng 12", None))

        self.nam.setItemText(0, QCoreApplication.translate("MainWindow", u"N\u0103m 2020", None))
        self.nam.setItemText(1, QCoreApplication.translate("MainWindow", u"N\u0103m 2021", None))
        self.nam.setItemText(2, QCoreApplication.translate("MainWindow", u"N\u0103m 2022", None))
        self.nam.setItemText(3, QCoreApplication.translate("MainWindow", u"N\u0103m 2023", None))
        self.nam.setItemText(4, QCoreApplication.translate("MainWindow", u"N\u0103m 2024", None))
        self.nam.setItemText(5, QCoreApplication.translate("MainWindow", u"N\u0103m 2025", None))
        self.nam.setItemText(6, QCoreApplication.translate("MainWindow", u"N\u0103m 2026", None))
        self.nam.setItemText(7, QCoreApplication.translate("MainWindow", u"N\u0103m 2027", None))
        self.nam.setItemText(8, QCoreApplication.translate("MainWindow", u"N\u0103m 2028", None))
        self.nam.setItemText(9, QCoreApplication.translate("MainWindow", u"N\u0103m 2029", None))
        self.nam.setItemText(10, QCoreApplication.translate("MainWindow", u"N\u0103m 2030", None))

        self.label_4.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng doanh thu n\u0103m:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Doanh thu th\u00e1ng hi\u1ec7n t\u1ea1i:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng s\u1ea3n ph\u1ea9m b\u00e1n ra:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng l\u1ee3i nhu\u1eadn th\u00e1ng n\u00e0y:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.xuat_bao_cao_button.setText(QCoreApplication.translate("MainWindow", u"Xu\u1ea5t b\u00e1o c\u00e1o", None))
        self.xuat_du_lieu_button.setText(QCoreApplication.translate("MainWindow", u"Xu\u1ea5t d\u1eef li\u1ec7u", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"So v\u1edbi th\u00e1ng tr\u01b0\u1edbc", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"So v\u1edbi th\u00e1ng tr\u01b0\u1edbc:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng chi th\u00e1ng hi\u1ec7n t\u1ea1i:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.chon_bao_cao.setText("")
        ___qtablewidgetitem5 = self.kho_table_widget.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"ID S\u1ea3n Ph\u1ea9m", None));
        ___qtablewidgetitem6 = self.kho_table_widget.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"T\u00ean S\u1ea3n Ph\u1ea9m", None));
        ___qtablewidgetitem7 = self.kho_table_widget.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Danh M\u1ee5c", None));
        ___qtablewidgetitem8 = self.kho_table_widget.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Gi\u00e1 B\u00e1n", None));
        ___qtablewidgetitem9 = self.kho_table_widget.horizontalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"S\u1ed1 L\u01b0\u1ee3ng T\u1ed3n Kho", None));
        ___qtablewidgetitem10 = self.kho_table_widget.horizontalHeaderItem(5)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"M\u00f4 T\u1ea3", None));
        ___qtablewidgetitem11 = self.kho_table_widget.horizontalHeaderItem(6)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Gi\u00e1 Nh\u1eadp", None));
        self.kho_chinh_sua_id_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID S\u1ea3n Ph\u1ea9m", None))
        self.kho_chinh_sua_ten_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"T\u00ean S\u1ea3n Ph\u1ea9m", None))
        self.kho_chinh_sua_id_danh_muc_combobox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn Danh M\u1ee5c", None))
        self.kho_chinh_sua_gia_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Gi\u00e1 B\u00e1n", None))
        self.kho_chinh_sua_so_luong_ton_kho_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"S\u1ed1 L\u01b0\u1ee3ng T\u1ed3n Kho", None))
        self.kho_chinh_sua_mo_ta_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"M\u00f4 T\u1ea3", None))
        self.kho_chinh_sua_image_drop_label.setText(QCoreApplication.translate("MainWindow", u"JPG", None))
        self.kho_chinh_sua_sua_button.setText(QCoreApplication.translate("MainWindow", u"S\u1eecA", None))
        self.kho_save_button.setText(QCoreApplication.translate("MainWindow", u"TH\u00caM", None))
        self.kho_nhap_hang_id_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID S\u1ea3n Ph\u1ea9m", None))
        self.kho_nhap_hang_ten_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"T\u00ean S\u1ea3n Ph\u1ea9m", None))
        self.kho_nhap_hang_so_luong_ton_kho_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"S\u1ed1 L\u01b0\u1ee3ng T\u1ed3n Kho", None))
        self.kho_nhap_hang_so_luong_ton_kho_line_edit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"S\u1ed1 L\u01b0\u1ee3ng Nh\u1eadp Th\u00eam", None))
        self.kho_nhap_hang_gia_nhap_san_pham_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Gi\u00e1 Nh\u1eadp", None))
        self.kho_nhap_hang_image_drop_label.setText(QCoreApplication.translate("MainWindow", u"JPG", None))
        self.kho_nhap_hang_nhap_button.setText(QCoreApplication.translate("MainWindow", u"NH\u1eacP", None))
        self.kho_chinh_sua_button.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ec9nh S\u1eeda", None))
        self.kho_nhap_hang_button.setText(QCoreApplication.translate("MainWindow", u"Nh\u1eadp H\u00e0ng", None))
        self.kho_tai_lai_san_pham_button.setText(QCoreApplication.translate("MainWindow", u"T\u1ea3i L\u1ea1i", None))
        self.kho_xoa_san_pham_button.setText(QCoreApplication.translate("MainWindow", u"X\u00f3a", None))
        self.kho_them_moi_button.setText(QCoreApplication.translate("MainWindow", u"Th\u00eam", None))
        self.chon_kho.setText("")
        ___qtablewidgetitem12 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem13 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"T\u00ean", None));
        ___qtablewidgetitem14 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Tu\u1ed5i", None));
        ___qtablewidgetitem15 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Gi\u1edbi T\u00ednh", None));
        ___qtablewidgetitem16 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ecba Ch\u1ec9", None));
        ___qtablewidgetitem17 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"S\u1ed1 \u0110i\u1ec7n Tho\u1ea1i", None));
        self.add_button.setText(QCoreApplication.translate("MainWindow", u"TH\u00caM", None))
        self.update_button.setText(QCoreApplication.translate("MainWindow", u"S\u1eecA", None))
        self.delete_button.setText(QCoreApplication.translate("MainWindow", u"X\u00d3A", None))
        self.id_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.name_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"T\u00ean Kh\u00e1ch H\u00e0ng", None))
        self.age_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Tu\u1ed5i", None))
        self.gender_line_edit.setItemText(0, QCoreApplication.translate("MainWindow", u"Nam", None))
        self.gender_line_edit.setItemText(1, QCoreApplication.translate("MainWindow", u"N\u1eef", None))

        self.address_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u0110\u1ecba Ch\u1ec9", None))
        self.phone_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"S\u1ed1 \u0110i\u1ec7n Tho\u1ea1i", None))
        self.show_history_button.setText(QCoreApplication.translate("MainWindow", u"XEM L\u1ecaCH S\u1eec", None))
        self.search_khach_hang.setPlaceholderText(QCoreApplication.translate("MainWindow", u"T\u00ecm ki\u1ebfm", None))
        self.chon_khach_hang.setText("")
        self.them_khach_moi.setText(QCoreApplication.translate("MainWindow", u"Th\u00eam kh\u00e1ch h\u00e0ng m\u1edbi", None))
    # retranslateUi

